export const FORESIGHT_WORKFLOW_ENV_VARS = {
    FORESIGHT_WORKFLOW_JOB_ID: 'FORESIGHT_WORKFLOW_JOB_ID',
    FORESIGHT_WORKFLOW_JOB_NAME: 'FORESIGHT_WORKFLOW_JOB_NAME'
}

export const FRAMEWORK_TYPES = {
    TEST: 'test',
    COVERAGE: 'test-coverage'
}
